name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Startup
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          file: ./Dockerfile
          tags: "tobiasgrether/perm8s-controller:${{github.ref_name}}"